name: Argon
on: [pull_request]
jobs:
  scan:
    name: Argon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f  # origin: v2.3.4
      - name: Argon Security
        uses: argonsecurity/scanner-action@cb7009df51790cede644c59211e436c5f3805f87  # origin: v1.0
        with:
          should-notify: true
          argon-token: "${{ secrets.ARGON_TOKEN }}"